title = "SEIR Extended Neighbors Test Scenario"

[simulator]
name = 'SEIR_Extended_Neighbors_Simulation'

[paths]
output_path = "simulation_data"
log_output = "simulation_logs"
neighbors_data_path = "simulation_conditions_data/neighbors/NeighborsMap-100by100-Agents100-Neighbors5-2025-10-04-203043Z.csv"

[simulation]
random_seed = 42
n_agents = 100
sim_duration = 365
initially_infected = 5

[agents]
beta = 0.01
e1 = 1
e2 = 3
t1 = 7
t2 = 14

[immunity]
lowest_immunity = 0.1
highest_immunity = 1.0
mask_beta_penalty = 0.75
mask_discipline_worst = 0.0
mask_discipline_best = 0.75

[age]
age_ranges = { 0 = [0, 9], 1 = [10, 19], 2 = [20, 29], 3 = [30, 39], 4 = [40, 49], 5 = [50, 59], 6 = [60, 69], 7 = [70, 79], 8 = [80, 89], 9 = [90, 100] }
age_probs = { 0 = 0.1125, 1 = 0.15, 2 = 0.2, 3 = 0.15, 4 = 0.2, 5 = 0.1, 6 = 0.05, 7 = 0.025, 8 = 0.00625, 9 = 0.00625 }
immunity_reduction_factors = { 0 = 0.2, 1 = 0.05, 2 = 0.0, 3 = 0.0, 4 = 0.05, 5 = 0.1, 6 = 0.15, 7 = 0.2, 8 = 0.25, 9 = 0.3 }

[pathogens]

[pathogens.linear_pathogen]
class = "LinearPathogen"
name = "LinearPathogen"
base_beta = 0.0
max_beta = 1.0

[pathogens.discrete_predefined_pathogen]
class = "DiscretePredefinedPathogen"
name = "DiscretePredefinedPathogen"
pathogen_values = [0.05, 0.06]
is_circular = true
