title = "Base SIR Scenario"

[simulator]
name = 'SIR_Simulation'

[paths]
output_path = "simulation_data"
log_output = "simulation_logs"

[simulation]
random_seed = 42
n_agents = 100
sim_duration = 365

[agents]
beta = 0.025
gamma = 0.01
